name: Bug report
description: Report a reproducible bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail to reproduce.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line description of the problem
      placeholder: Graph rendering fails when...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps and, if possible, a minimal input JSON
      placeholder: |
        1. Run ...
        2. Use this input ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: GraphRender version
      placeholder: 0.1.0

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, and install method
      placeholder: macOS 14, Python 3.12, pip install -e .
